version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app:ro # bind mount, macht es möglich Aktualisierungen in docker zu übertragen!
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=password123
      - DATABASE_NAME=fastapi_course
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=SomethingisWonderful12345MALSEHEnDAsGEHTBESSER
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=fastapi_course

    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
