name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job1:
    env:
      DATABASE_HOSTNAME: localhost
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: Zauberer
      DATABASE_NAME: fastapi_course
      DATABASE_USERNAME: postgres
      SECRET_KEY: SomethingisWonderful12345MALSEHEnDAsGEHTBESSER
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    runs-on: ubuntu-20.04
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: "install python v 3.10"
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: "update pip with linux command!"
        run: "python -m pip install --upgrade pip"
      - name: "install app dependencies via pip"
        run: "pip install -r requirements.txt"
      - name: "unit testing with pytest"
        run: pip install pytest
          pytest
